# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
    # Use the same Docker base as the project
      - image: circleci/node

    working_directory: ~/repo

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - run:
          name: build and upload image
          command: |
            cd ~/repo
            docker-compose -f docker-compose-build.yaml build --parallel
            docker login --username=$DOCKER_USER --password=$DOCKER_PASS
            docker-compose -f docker-compose-build.yaml push
